### ISSUE TITLE
Screenshots saved to Desktop - Coords.txt blank

### ISSUE THREAD

**Issue by PPartisan** [loicNorgeot/THE_LONG_DARK#3]
I set up my map and screenshots directory on my external hard drive, then spent a couple of hours walking around. For whatever reason though, the screenshot files all saved to my desktop (there were quite a few when I stopped playing!). The originally marked screenshots folder was empty and the cords.txt file was empty. Any ideas? I still have the screenshots saved for now in case they're of any use.

**Comment by sulli42** [comment]
Yea, there is something buggy with the script. You have to set your screenshot folder to desktop, the script reads the coordinates from the screenshot then deletes it, they won't stay on your desktop. The only way I could get it to work properly was to set my map directory first then screenshot directory (to desktop), then start TLD, then tab out and click the start mapping button. Go back to game and hit F7. Should start mapping. Also I can't seem to stop the program till I quit TLD. Then I can click create map. And all is good, it's a bit clumsy but in the end it works.


Sent from Outlook Mobile






On Tue, Jan 19, 2016 at 12:25 PM -0800, "Tom Calver" <notifications@github.com> wrote:





I set up my map and screenshots directory on my external hard drive, then spent a couple of hours walking around For whatever reason though, the screenshot files all saved to my desktop (there were quite a few when I stopped playing!) The originally marked screenshots folder was empty and the cordstxt file was empty Any ideas? I still have the screenshots saved for now in case they're of any use

---
Reply to this email directly or view it on GitHub:
https://github.com/loicNorgeot/THE_LONG_DARK/issues/3

**Comment by PPartisan** [comment]
That works, thanks :+1: - Might be worth putting this in the ReadMe file too?
